### ISSUE TITLE
Action nodes redesign to improve visual canvas' readability

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1701]
### Description
Currently, all the action nodes have the same format(Label-sublabel) which works for few, but not for the others. This is demanding a redesign sooner or later.
The redesign's goal is to improve the overall readability of visual canvas through a flexible design system – you should be able to quickly scan through it and understand the flow, where to find what. 

### Execution plan
- [ ] (in PR #2005 ) Layout: smart layouter, support size-sensitive node blocks
- [ ] (in PR #2017 ) Widget: enhance the appearance of `SetProperties` as a multi-line node, extract shared elements
- [ ] Widget: implement multi-section node widget which is split by '-------v-------', apply to specific $types
- [ ] LG: Syntax hightlighting lib of LanguageGeneration(LG) text 
- [ ] Layout: node size adjustment and node styles fine tune

### Other context
Design link: https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=4585%3A1049

**Comment by yeze322** [comment]
It's really nice!

**Comment by sangwoohaan** [comment]
@hibrenda Could you add this to the R8 design discussion as well?

**Comment by sangwoohaan** [comment]
adding https://github.com/microsoft/BotFramework-Composer/issues/1476

**Comment by mareekuh** [comment]
Per design review:
@sangwoohaan  - due : 01/28
1. - Add the name of the action in the label, in addition to the action type (Begin **Help (dialog)**)
2. - Keep body of node white
3.- If there are input values, list them vertically 
4. -If there are output values, list them below a line  ----v----- 
5. - @sangwoohaan 
- Create update a page like this (screenshot) that includes different types of node so Marc can see the nodes in context when designing the final visuals
- Create a sample node for each of the different types of actions : use this list as a starting point. Do Prompt nodes last (as they are more complicated)

<img width="470" alt="Screen Shot 2020-01-25 at 6 50 23 PM" src="https://user-images.githubusercontent.com/48503434/73129931-93cb1300-3fa3-11ea-84d2-debe70e48f36.png">

@DesignPolice - Start on final design on 01/28. Due: 01/31 
FYI for @cwhitten

**Comment by mareekuh** [comment]
Oops clicked wrong button

**Comment by sangwoohaan** [comment]
Final design : https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=4585%3A1049

**Comment by DesignPolice** [comment]
@Kaiqb I think this one is in progress. Does anyone else have other design needs?

**Comment by yeze322** [comment]
> @Kaiqb I think this one is in progress. Does anyone else have other design needs?

Awesome work! Alan and I are taking actions on it 💯 

Just want to check two extra things:
1. A choice can have `synonyms`, do we want to show it?
![image](https://user-images.githubusercontent.com/8528761/75213207-60f38500-57c4-11ea-9a8c-b70d23620901.png)
2. There is a `DeleteProperties` type which is quite similar to `SetProperties`. Do we want to show it as a list?
![image](https://user-images.githubusercontent.com/8528761/75213284-94361400-57c4-11ea-9720-8500b6adb5d7.png)

@sangwoohaan @DesignPolice

**Comment by yeze322** [comment]
Execution plan:
- [ ] [layout] Smart layouter: support size-sensitive node blocks - #2005 
- [ ] [widget & sdk] Enhance the appearance of `SetProperties` as a multi-line node, extract shared elements - #2017 
- [ ] [widget & sdk] Implement multi-section node widget which is split by '-------v-------', apply to specific $types
- [ ] [lg] Syntax hightlighting lib of LanguageGeneration(LG) text 
- [ ] [layout] node size adjustment

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2136
