### ISSUE TITLE
Add support for loading plugin extensions into Composer

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#1928]
Composer must support connectivity to outside services, and allow outside services to plugin and extend the capabilities of the Composer editor. This will be achieved by exposing a series of APIs to external plugins that can be loaded dynamically into the application and, by calling the APIs, hook into key areas of Composer.

The first round of plugin functionality is focused on the low level plugin architecture as well as extension points for storage, authentication and publishing.

This is a tracking issue for a bunch of sub-tickets that will define the work necessary to implement this feature.

## Scenarios

* Allow Composer to store/load content in a database or remote storage
* Allow Composer to use AAD for authentication
* Allow Composer to publish a bot to a remote runtime
* Allow Composer to publish a bot directly to a Git repo
* Allow Composer to use a custom database or API for authentication

### Finish Plugin Loader

An in progress version of the plugin loader is in the `benbrown/storage branch` [specifically in this file](https://github.com/microsoft/BotFramework-Composer/blob/benbrown/storage/Composer/packages/server/src/services/pluginLoader.ts).

Basically the way it works is that there is a single instance of the plugin loader that has access to the Express webserver instance. When the app launches, the plugin loader looks for plugins in the plugins/ folder and loads everything it finds. It will require in the main file, then look for an initialize function. 

When loading the plugin, Composer gives the plugin code limited access to Composer and a special plugin namespace. Plugins can currently set up a storage provider, an auth provider, or add custom web routes and middleware.

From within the main Composer app, features access the plugin namespace via the plugin singleton. For example, [use of a custom storage provider is implemented here](https://github.com/microsoft/BotFramework-Composer/blob/benbrown/storage/Composer/packages/server/src/models/storage/storageFactory.ts)

Additional work to finish the plugin loader implementation:

- [x] Refine APIs used to expose Composer features @benbrown 
- [x] Add an instance of PassportJs and necessary accessor features so that plugins can access auth and identity @benbrown 
- [ ] Expose a settings page that controls Composer-wide settings that will be made available to plugins, such as a database connect URI used with storage or a oauth client id used during authentication.
- [x] Remove the prototype plugins from this repo @benbrown 
- [ ] Publish a package of classes and interfaces usable by plugin developers 

### Publishing Plugins

Ben has implemented a v1 of publish plugin loader. This allows a plugin to register methods for publish, get status of publish, get publish history, and rollback.

- [ ] Design/ux for the "Publish" page in composer that will allow publishing, managing of publish destinations
- [ ] #1945 Implement necessary Express routes for executing publish actions
- [ ] Implement a plugin that encapsulates communication with and management of the local bot runtime used during testing - in progress in #1952 
- [ ] ~Implement a plugin that encapsulates communication with ABS-H?~

### Storage Plugins

Ben has implemented a v1 of storage driver plugin loader, as well as a MongoDB backed storage provider.

- [x] Implement the ability to load an external storage plugin
- [x] Investigate possibility of storage plugin to be a singleton instead of a newly instantiated instance for each use (bad for database connections)
- [ ] Refactor blob storage into a plugin
- [ ] Refactor filesystem storage into a plugin? (alternatively, leave this as built-in default)

### Auth Plugins

- [x] Implement a wrapper for PassportJS in the plugin loader @benbrown 
- [x] Implement an accessor so that plugins can access the identity information made available by Passport without access to the request object
- [ ] Implement an AAD plugin

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2023
