### ISSUE TITLE
Recognizer & Trigger wizard in Composer 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2394]
## Context
Recognizer and triggers are core concepts for creating dialog in bot framework composer. Recognizer Type and triggers are tightly connected in some scenarios in dialog developing. In order to support more recognizer types inside composer, simplify the creation process and extend the user customization requirement, we  proposed following recognizer changes and corresponding trigger wizard updates. 

## User Scenarios 

Scenario 1: To enable QnAMakerRecognizer, user can not only hook up with QnA through UnknownIntent-> QnA action but also deep integration QnA to get the response with $Answer from user’s KB. 

Scenario 2: To enable CrossTrainedRecognizerSet for LUIS and QnA, user can choose what action need to be taken if there is ambiguity for user’s utterance. As it may hit both the LUIS intent and QnA Question.  

Scenario 3: To enable multi-local settings for multi-language recognizer. Multi-lang recognizer structure has been supported in Composer GA, now we need to add a non-default locale to LUIS and QnA recognizer. So that different languages could be recognized for LUIS and QnA.  

Scenario 4: To accept Adaptive Card payload. Adaptive card is widely used in bot responses. If user would like to send back card updates to bot, bot should have a trigger to be the callback for this payload. So we need to support trigger wizard to include AdaptiveCard scenario. 

Scenario 5: To support customized recognizer type. User may want to add multi-lang support for regex or add entity configuration for RegexRecognizer. Meanwhile, user can also add other 3rd party recognizer for each dialog.  

## Task Breakdown 
- [ ] New recognizer drop down :  Default recognizer , Regex recognizer, Custom recognizer
- [ ] New trigger wizard : OnQnAMatch 
- [ ] New trigger wizard : , OnChooseIntent
- [ ] New trigger wizard : OnIntent(AdaptiveCard)
- [ ] Legacy bot migration to new recognizer hierarchy 
- [ ] Validation check for recognizer switching 
- [ ] Support QnA build 

[Design Spec] https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/EWSmZ6UhsMlKnpbc1lKhhbEB0GZdoLCAtMf8rlHdHDZHvg?e=AXzdQq

[Figma Design]
 https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-%2F-UI-library?node-id=2392%3A20262

**Comment by cwhitten** [comment]
Closing in anticipation of https://github.com/microsoft/BotFramework-Composer/issues/3463
