### ISSUE TITLE
Multi-language tech spec

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#3348]
MultiLanguage Tech Spec

## RoadMap
- [] Stage1: lg, lu multiLanguage authoring
- [] Stage2: Qna multiLanguge authoring
- [] Stage3(P2): adavanced features like translator

List out some open questions to be decided

## Data persistence

Current bot structure already setup a convention for locale-specific language assets to save on disk. The open question is about how to save the settings: how many languages we support and which one is the default. 

### Do we a) explicitly save the supported language list, or b) we infer the supported language list from assets discovered? 

Basically approach a will serialize as 
```jsonc
{
 "languages": [
      "en-us" ,// the first one is default language
      "fr-fr"
 ] 
}
```

approach b will just like
```json
{
"defaultLanguages": "en-us
}
```
Approach a, good side is straightforwad, and have the capability to disable\enable certain locale without touching assets or other features like fallback order, but have redunancy and thus potential inconsistency

Approach b, requires a little bit more effort, but have no duplication and no space for more features like dsiable\enable\fallback order. 

I will vote A. 

Notes:
Maybe related to SDK conversion if any. 

###  Do we save it in appsettings.json or do we want to redesign\split the settings first and find a good place for it?

I will vote for save it into appsettings.json for now, ie, not have multi-langage effort depends on the refactor\restructure of settings

## Data syncing 

The core issue is how much we can and need to do to keep the data between language sync.  The principle i assume now is we should try to keep the structure of language assets sync. 

### When adding a new locale, do we create a full copy of the default locale's language assets?
I assume yes. 

### In design page, when adding a new lg template, do we auto-matically add the same template from all other languages? 

I assume yes? and with the same content, because if not adding other language, then there will be an error if the bot is asked with other languages.

### In design page, when deleting a lg template (or other) in default locale, do we auto-matically deleting the same template from all other languages?

I assume yes? LU is probably a yes, because if not clean up lu, the model is not behaving right, but for lg, there is no harm to keep it. 

### In all up view, if user add\remove assets, do we want to auto-sync with other languages?

I assume no? because in all up view, it's designed to be fully owned by user.

### We need to validate for all languages listed, the reference in dialog is valid, right? 

I assume yes, the dialog must be valid at every language

### Do we do validation for different structure even if they are all valid with dialog?

I assume we only validate the correctness between language assets with dialog assets, not looking into difference between language assets.  We can detect the difference and show "info" maybe.
