### ISSUE TITLE
Tracking: Improvements to Publishing

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3387]
This issue exists to track progress on the publishing tools to go from "preview" to "full release"

# Related issues:

- [x] #3328 - Improve formatting and content of logging output displayed in publishing UI
- [x] #3320 , #3300 "undefined is not a valid target" bug
- [x] #3272 - add javascript runtime and refactor out language specific actions into the plugins
- [ ] #3385 - add ability to provision environments
- [ ] #3384 - add login to azure
- [ ] #3386 - update publishing to use azure login
- [ ] Improve error handling during publish
