### ISSUE TITLE
Feature flag enhancements 

### ISSUE THREAD

**Issue by pavolum** [microsoft/BotFramework-Composer#4513]
The first feature flag implementation in R11 covered all core scenarios, in the next milestone the following enhancements are needed:

**Tasks:**
- [ ] Add UI and back end functionality to toggle all feature flags to false at once (per design spec)
- [ ] Add feature flag groups (per design spec)
- [ ] Feature flag values available to extensions
- [ ] Feature flag values available to Electron Main process (initial thoughts to piggy back on electron flow where user changes usersettings like locale and makes that visible to the main process)
- [ ] Add ability to configure hidden feature flags when running electron app
- [ ] Crete unit tests for all feature flag scenarios

**Comment by cwhitten** [comment]
@pavolum please look these tasks over and update anything needed, or close this ticket entirely if it is now stale

**Comment by mewa1024** [comment]
for reference, the design spec is here: https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-UI-library?node-id=6556%3A37398
