### ISSUE TITLE
Dialog Navigation & Event IA updates

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#693]
Design
- [x] New design for url and navigation https://github.com/microsoft/BotFramework-Composer/issues/746

Implementation
- [x] Adjustment on left nav (show triggers/events, layout adjustment, display name for "Main") https://github.com/microsoft/BotFramework-Composer/issues/736
- [x] Adjustment in visual editor (render trigger\event as a node), remove "events" view https://github.com/microsoft/BotFramework-Composer/issues/740
- [x] Shell/Visual editor coordination with new navigation\url design https://github.com/microsoft/BotFramework-Composer/issues/786
- [x] sync up with 4.future new schema 
https://github.com/microsoft/BotFramework-Composer/issues/769
- [ ] New trigger wizard https://github.com/microsoft/BotFramework-Composer/issues/759
- [ ] Trigger node on visual editor accepting utterances/phrases/etc.
- [x] Dialog filter https://github.com/microsoft/BotFramework-Composer/issues/760
- [x] Reduce overall space

## Task Track

| Item | Owner | Status
| - | - | -
| [X] New URL design for new Event\Action UX  https://github.com/microsoft/BotFramework-Composer/issues/746  | Dong | Done
| [X ]  Adjustment on left nav (show triggers/events, layout adjustment, display name for "Main") https://github.com/microsoft/BotFramework-Composer/issues/736 <br> ---- [X] Align UI in left navigation (display name for "Main", Look and feel for left navigation , composer head and toolbar) https://github.com/microsoft/BotFramework-Composer/issues/750 <br> ---- [X] Show trigger list on dialog navigation (trigger UX, breadcrumb, url)  https://github.com/microsoft/BotFramework-Composer/issues/766 | LeiLei | S11 - Done
| [X] [Dialog Navigation & Event/Action] show only steps in the canvas https://github.com/microsoft/BotFramework-Composer/issues/740 <br> --- [ ] need to support "add trigger" if the dialog is new https://github.com/microsoft/BotFramework-Composer/issues/786 | leilei | S13
| [X] [Dialog navigation and events] Sync-up with 4.future new schema for composer bot project https://github.com/microsoft/BotFramework-Composer/issues/769 <br> --- [X] need to support 4.future new schema in visual editor https://github.com/microsoft/BotFramework-Composer/issues/787  | Ze / Lu | S12
| [ ] New trigger wizard https://github.com/microsoft/BotFramework-Composer/issues/759 | weitian | S13
| [ ] need to align with new schema for "add trigger" menu and the wizard as well https://github.com/microsoft/BotFramework-Composer/issues/825
| [ ] Dialog filter https://github.com/microsoft/BotFramework-Composer/issues/760 

- OpenItems
    - 8/30 will adopt simple version of "new trigger wizard" and then update the advanced version later
