### ISSUE TITLE
Deploy from Composer to ABS using BF CLI tools

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#699]
When a new bot project is created in composer, in addition to the Main dialog, composer will also include a copy of the bot runtime code.  As a result, the project will be “deployable”, to Azure Bot Service, from the very moment it is created. The built in runtime used to test within Composer does not have to play double-duty as the deployable app.

Developers can then modify their bot runtime and test it locally using standard tools and best practices offered by the Bot Framework SDK. 

[Please read scenarios doc here](https://microsoft-my.sharepoint-df.com/:w:/g/personal/benbro_microsoft_com1/ETROpTXEgJRCthu5k7Tq3JEBrbQRRVPqDQmrzaK0B8uJ3w?e=tfM3X7)

## all scripts needs to check PowerShell 6
Check if PowerShell is installed on local machine 
If not, show error message when PowerShell 6 is not installed on device. Error should include a link to download PowerShell 6. Show download instruction per OS: 
- Windows - https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6
- Mac -  https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-6

## Create new deployable Runtime [See Doc](https://microsoft-my.sharepoint-df.com/:w:/g/personal/benbro_microsoft_com1/EYAiZeKB-DxMvojvP1P2AgcBaIuQUx5mQsbzSHTKV47jEw?e=QvPb6q)
- [x] Create a new folder for the deployable runtime. This could go in `BotProjects/`
- [x] Make runtime load content from a standard folder visible in the project `ComposerDialogs/`
- [x] Remove any admin- or composer- facing API endpoints. Only the /api/messages url should remain.
- [x] Convert the deployable bot runtime generated for composer, into an SDK template.
- [x] Add middleware for using Application Insights. Use values from environment to configure. If values are not present, emit a console warning. Bot continues to run/function normally.
- [x] Add middleware for transcript logging to Azure storage.  Use values from environment to configure, if values are not present, emit a console warning. Bot continues to run/function normally.
- [x] add middleware for Bot Inspector to help debugging of bots deployed to Azure.
- [x] Add CosmosDB storage and configure with values from environment - without a data store, bot should error out. 
- [x] Put deploy CLI scripts (#737) in a special Deployments folder.
- [x] include ARM JSON templates for resource creation with predefined defaults. Developers can modify as needed.
- [x] include an ARM parameters files, with default param for all required resources. This file is used to create the Azure resources, allow users to change settings, and acts as a sample.
- [ ] Include a controller, middleware, and manifest file for exposing the bot as a skill.
- [x] Create placeholders for all necessary environment variables in appsettings.json

## Include runtime in all newly created Bot projects
- [x] When a bot project is created, a copy of the deployable runtime should be added to the folder
- [x] Move all composer-managed content into a subfolder of the bot project folder called `ComposerDialogs/`

## Allow full control over destination path for bot projects
- [x] When creating a new bot project, user should be able to use a system file browser to choose the destination for the new project.  This should not be limited to the SampleBots/ folder within composer. @benbrown
- [x] When opening a bot project, user should be able to browse the file system to choose a project to open. @benbrown

## New CLI tools: create and deploy (Continuation of #737)
Create 2 command line scripts that use ARM templates and the az cli to provision the necessary Azure resources, configure the project with environment settings, and deploy the code to those resources.

### create.ps1
- [x] Accept a bot name, environment name (single word, all lowercase), 16-character password, an Azure region (location), and a LUIS authoring key as parameters
- [x] For any missing parameter, prompt the user interactively for the value
- [x] for LUIS authoring key from EU, make sure LUIS apps are created only in EU regions. 
- [x] create all resources within the same Azure region
- [x] Create descriptive names for all resources based on the bot name - for example, (botname)-(environment)-webapp (botname)-(environment)-group (botname)-(environment)-serviceplan 
- [x] Create app registration
- [x] capture the appID resulting from the app registration, report it back to the user on console and log it
- [x] create a new Resource Group
- [x] create App Service plan
- [x] create web app service
- [x] create CosmosDB
- [x] create Azure Storage
- [x] Upon any error, display the error in full detail, and stop process
    - [x] capture common error: access denied
    - [x] capture common error: resource already exists
- [x] create LUIS Cognitive Service key, in given bot region
- [x] create LUIS apps for specified environment and capture resulting app IDs
    - [x] LUIS app names should be generated in the same way they are inside Composer, botname(environment)-dialogname
    - [x] if environment already created inside Composer, use existing LUIS apps
    - [x] P0 assume Composer ran its language creation and orchestration process.  The create and publish scripts should use LUIS JSON flies from the generated folder 
    - [ ] P1 Extract the orcanstration for managed LU process from Composer into a CLI lib that can be used from the script and run directly on LU files
- [x] assign LUIS Cognitive Service keys to LUIS apps
- [x] Run the necessary ludown/luparse commands to process the .lu files
- [x] Publish all apps to LUIS 
- [x] If error encountered in publish to luis, stop script and display error message
- [x] Write values to appsettings.json in appropriate place
- [x] Upon success, display the resulting values, including: app id, app password, resource group name, web app name, web app API endpoint url

### deploy.ps1
- [x] Accept bot name, environment name, and LUIS authoring key as parameters
- [x] Run the necessary ludown/luparse commands to process the .lu files
- [x] Publish to LUIS
- [x] If error encountered in publish to luis, stop script and display error message
- [x] Make any necessary changes to appsettings.json (add additional LUIS app ids?)
- [x] Create zipfile of project folder
- [x] Deploy the zipfile to web app hosting your bot
- [x] If an error is encountered in deploy of zipfile, display error message

## Composer Deploy Instructions page
a new page will be made inside composer that includes copy-pasteable versions of the `create.ps1` and `publish.ps1` commands described above with the bot's name and LUIS authoring key pre-filled.

[Design assets are here](https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/UX-and-App-model?node-id=1321%3A3996) 

 @benbrown

## Task Track

| Item | Owner | Status
| - | - | -
| [ ] Create deploy runtime (composer bot project template) https://github.com/microsoft/BotFramework-Composer/issues/770 | Lu/Qi | S13
| [X] need cli-based script for creating the resource on Azure https://github.com/microsoft/BotFramework-Composer/issues/723 | Qi | S12
| [ ] Handle Luis deploy (best effort) | Lu/Qi 
| [ ] File browse in new bot / open bot | benbrown | #794 

Open Items
 - 8/30 Require design for the information instructions page
 - 8/30 @Ben  open ask/ question about choosing a specific folder vs. using convention
