### ISSUE TITLE
Environment variable management

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#700]
Tech Design
- [x] Design for how\when\where settings is persisted and used https://github.com/microsoft/BotFramework-Composer/issues/749

Runtime
- [x] update bot runtime to pick\merge settings from bot folder (including customized settings) https://github.com/microsoft/BotFramework-Composer/pull/719

App
- [x] make sure settings per bot https://github.com/microsoft/BotFramework-Composer/pull/719
- [x] persisting settings in bot folder (local storage) https://github.com/microsoft/BotFramework-Composer/pull/719
- [x] keep sensitive information in local storage and filter sensitive information when persisting https://github.com/microsoft/BotFramework-Composer/pull/719
- [x] update bot runtime to pick\merge settings from bot folder (including customized settings) https://github.com/microsoft/BotFramework-Composer/pull/719

UI
- [x] support edit bot settings in Composer 
- [ ] ability to copy a bots settings to clipboard
- [x] support edit customized settings (can also be together with luis/oauth/etc)

## Task Track

| Item | Owner | Status
| - | - | -
| [x] Design for how\when\where settings is persisted and used https://github.com/microsoft/BotFramework-Composer/issues/749 | Dong | S11
| [X ] Implementation for environment variable setting (per bot) https://github.com/microsoft/BotFramework-Composer/issues/719 | Wenyi | S11 & S12
| [ ] UX design for environment variable setting in composer https://github.com/microsoft/BotFramework-Composer/issues/777 | Sangwoo
| [ ] Support setting page in composer client (align with UX design) |
 
https://microsoft-my.sharepoint.com/:w:/p/cwhitten/EbJoNLILy9JOpZz2Syu4fIgBMhbSJtJKoxyFP0HcZV_9Tg?rtime=pPZZy_wh10g
